### ISSUE TITLE
Discuss software patterns in Key Code Concepts documentation

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#12]
It would be great if we could break all of these down into known software pattern descriptions so we can easily describe that as well as educate.
https://github.com/WheelMud/WheelMUD/blob/fd6ee4f1f213bfc3785384961f2001c42f46c6c9/Documentation/Development/KeyCodeConcepts.md

**Comment by duaneking** [comment]
Exactly my request earlier; thanks for opening this.

**Comment by DavidRieman** [comment]
Clearly a good, recently discussed example to add to this document (or even its own sub-page) would how we use the Repository pattern in the DAL for things like looking up PlayerRecords.

**Comment by DavidRieman** [comment]
Migrated to base repo issues
