### ISSUE TITLE
Remove 'created by' and 'edited by' lines from file headers.

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#14]
Currently it seems there is either no value, or even negative value, in having those lines be present.  We should remove them from the source, and adjust our documents to recommend against the process (discussed in CodingStandards.md)

**Comment by duaneking** [comment]
Yeah the focus should be a working product not a little glory for editing a file to fix a capital letter.

**Comment by axiomatic-io** [comment]
Completed revisions and I'm ready to make a pull request

**Comment by axiomatic-io** [comment]
Can we close this issue as completed?

**Comment by DavidRieman** [comment]
Nearly.  I think the second half remains - we should add some notes recommending contributors to let git history be our file history solution, leaving update/create/etc history out of the headers - to the CodingStandards doc (https://github.com/WheelMud/WheelMUD/blob/master/Documentation/Development/CodingStandards.md)

**Comment by DavidRieman** [comment]
Closing; this was addressed by #36 and #37.  Thanks!

**Comment by DavidRieman** [comment]
PS: Pushed fixes for a few more I found.
