### ISSUE TITLE
Fix debugging warning when using F5 on WindowsService project

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#15]
The debug settings seem correct, so not sure why it thinks it is optimized.  Might just need to recreate the project.

Personally, while we are at it, I think we can just combine the WindowsService and TestHarness projects while fixing this - so we have a single project that runs the way WindowsService does now (IE apparently as a service but with Interactivity enabled we see an output console), but also allows you to enter administrative or test Commands the way the TestHarness does (including any existing TestHarness commands).  Maybe name that project "Server"?  Ensure the project does not complain about optimized things when using F5 on Debug flavors.

**Comment by duaneking** [comment]
Yeah I think how Minecraft did this is best; one server and admin console commands as needed ; seemed to work well for them. Even if not, I think one server will ease the development burden.

**Comment by DavidRieman** [comment]
Going to try this now  :)

**Comment by axiomatic-io** [comment]
So is renaming the TestHarness project all that remains to be done?

**Comment by DavidRieman** [comment]
I believe so!

**Comment by DavidRieman** [comment]
The project is now "ServiceHarness" and it builds "WheelMUD.exe".  Closing.
