### ISSUE TITLE
Migrate Documentation into GitHub

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#3]
Migrate documentation again, from CodePlex Documentation areas, into github via ReadMe documentation file trees.

**Comment by duaneking** [comment]
We can have a branch dedicated to the website on github, and it would update the site every time it gets checked into.

**Comment by DavidRieman** [comment]
pull/11.  Some documentation still has some line spacing issues, table formatting issues, and so on, but the bulk is in place and formatted reasonably, and the content is updated to reflect reality now.  Keeping this open until I get to do another cleanup pass.

**Comment by duaneking** [comment]
I made a lot of comments/questions; going to wait and let you read t all and pull when you say your ready.

**Comment by DavidRieman** [comment]
So, what remains to be migrated are a bunch of 'pinned design discussions' from the forums that served as living design documents.  I've migrated the World Interaction User Story, but there are about a dozen more documents on my list to recreate... hopefully in a manner that renders nicely in markdown.  (Also I am thinking about seeing if I can get that first user story to look nice in markdown as well, but it depends on .md giving me control of background color, text color, etc.)

**Comment by duaneking** [comment]
I think "living" documents should be checked in, don't you?

**Comment by DavidRieman** [comment]
Yes, even if I can't get it to render nicely in markdown, source control is still the right answer.  :)

**Comment by axiomatic-io** [comment]
Can you point me to the docs in the old forums so I can try to port them to Markdown format?

**Comment by DavidRieman** [comment]
There are two places.  I have an archive somewhere of the original forums files, but it's not exactly easy to share.  The other is that the relevant bits were _hopefully_ copied to http://muds.gamedev.com, just with poor formatting and will have to be searched out case by case ATM.

ATM I'm not sure where I kept that "list" I reference of documents I wanted to recreate.  Off the top of my head though, we need to track down a form of the project roadmap, and the "user stories" were pretty cool representations of our design vision/direction on some key areas, especially when formatted well to look like an actual telnet session.

**Comment by axiomatic-io** [comment]
Can we use the GitHub wiki feature to host the documentation?

**Comment by DavidRieman** [comment]
> GitHub wiki feature?
I prefer documentation in the actual main repo:
* The documentation will be available offline to developers, by default.  (e.g. Travelling with a laptop.)
* Encourages a world where the developer commits documentation updates at the same moment that the documentation would otherwise become outdated.  There is literally no period of time where the two are out of sync, when adhering to this strategy.
* Beyond enabling the above, it enables the option for us to block PR requests that don't make suitable documentation updates to accompany a change.  I'm not saying we _would_, but the option is there if we want it.

**Comment by DavidRieman** [comment]
Here's a good one to try updating: http://muds.gamedev.com/mudforum/index.php?t=msg&goto=275

**Comment by DavidRieman** [comment]
I found a list of design articles we had that would serve as a good high-priority migration list.  I don't think they were all formatted with the nice User Stories approach so some may be easier to migrate than others.

DESIGN ARTICLES:
* World Interaction User Story
* Weight, Volume...?
* Quests
* Bounty System
* Grouping User Story
* Trading User Story
* Non-Killing XP ?
* Item Properties and Behaviors
* Non-Reboot Code Updates
* Flashback
* Socials
* "Commands" command
* Weapon Combat - Real Time
* Stacking / Non-Stacking
* part of "Mob Attributes" ?
* Control and Relinquish.
* Converse Mode
* Board, Note, Scribe
* OnLine world Creation (OLC)
* Everything as a Behavior

**Comment by DavidRieman** [comment]
Migrated to base repo
