### ISSUE TITLE
Replace wheelmud.net/Forums references

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#30]
There are a handful of TODO comments pointing at forums discussions.  Will need to find/secure the related content and point the TODOs at their new locations.

**Comment by axiomatic-io** [comment]
I don't see any TODOs that reference forum discussions. Has this issue been addressed?

**Comment by DavidRieman** [comment]
It's still relevant - they are still in there like "http://www.wheelmud.net/tabid/..."

**Comment by axiomatic-io** [comment]
Does the content that needs to be linked to exist somewhere in here? http://muds.gamedev.com/mudforum/index.php?t=thread&frm_id=9&rid=0 ?

**Comment by DavidRieman** [comment]
Theoretically, yes.  But I don't recall with certainty now if that mostly-manual backup process was completed.  And honestly, that forum isn't the best place either, and the formatting for copied content was not good at all - If we could create GitHub issues to track and link the TODOs against would be much better.

There's also a list of the old issues that were from the time we tried to manage that on codeplex, with issue texts still available on the codeplex archive (sans additional issue properties) - https://archive.codeplex.com/?p=wheelmud

**Comment by duaneking** [comment]
We should migrate that documentation as soon as possible; The gamedev.com domain is owned by me right now, but may not be much longer.

**Comment by duaneking** [comment]
The gamedev domain will be decommissioned and taken offline in 2 weeks by godaddy, who gave me NO PRIOR WARNING for this sudden and inconsiderate action as they are FORCING all servers of the type I am on to be taken offline and junked, so I have no power over this.

**Comment by duaneking** [comment]
@DavidRieman

**Comment by DavidRieman** [comment]
The last few of these references have been removed.
