### ISSUE TITLE
Internet domain names

### ISSUE THREAD

**Issue by hectorsosajr** [WheelMud/WheelMUD#32]
I would like to pass the wheelmud.net and wheelmud.org domains to you guys. I just renewed wheelmud.org as I didn't want it to fall into other hands. Just let me know where to send the transfer requests and I'll get this started.

**Comment by duaneking** [comment]
I can catch this.

**Comment by DavidRieman** [comment]
Already took care of it by email.

**Comment by hectorsosajr** [comment]
Domains have been transferred. 👍
