### ISSUE TITLE
Try replacing custom WeakReference<T> with built-in ones

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#40]
I believe the built-in system WeakReference<T> did not exist when we built the WeakReference<T> helper utility.  We should try switching to the built-in one and deleting our custom one if no longer needed.

**Comment by axiomatic-io** [comment]
What does WeakReference do in the project context?

**Comment by axiomatic-io** [comment]
Looking at the code, we would need to refactor from this:
`PlayerBehavior playerBehavior = this.playerBehavior.Target;
if (playerBehavior != null)
{
    return playerBehavior.BuildPrompt();
}`
to this:
`PlayerBehavior playerBehavior;
if(this.playerBehavior.TryGetTarget(out playerBehavior))
{
    return playerBehavior.BuildPrompt();
}`

**Comment by axiomatic-io** [comment]
There will be a little refactoring needed since the Target property doesn't exist on the System version. There is a TryGetTarget method instead.

**Comment by DavidRieman** [comment]
A weak reference keeps a reference to a thing without keeping it alive.  For example that is probably a good usage:  The FollowingBehavior uses it to keep track of the target that is being followed.  Even if the target is a player who logs out, that player's object tree should not be kept in memory just because someone was following them.

Our WeakReference<T> I believe was pretty much just a wrapper for weak references that typed the target property for convenience.

**Comment by axiomatic-io** [comment]
There's no harm in leaving it if it makes the code clearer.

**Comment by DavidRieman** [comment]
Wow, I'm surprised they went that direction.  Yeah, I like ours better.  Maybe we can name it `SimpleWeakReference` or something though, to differentiate without ambiguity?

**Comment by axiomatic-io** [comment]
Done and committed.

**Comment by axiomatic-io** [comment]
The filename for the class was WeakReferenceTyped even though the class was originally named WeakReference. Would you like me to change the filename to match the new classname SimpleWeakReference?

**Comment by DavidRieman** [comment]
Yes please

**Comment by axiomatic-io** [comment]
Done and committed.

**Comment by DavidRieman** [comment]
Thanks!
