### ISSUE TITLE
NullReference on SQLite provider

### ISSUE THREAD

**Issue by axiomatic-io** [WheelMud/WheelMUD#41]
Hi Everyone,

I'm getting a null ref when the world data tries to load. The code tries to get the SQLite provider but it is null. This just started happening and even happens when I pull down the last good commit from the non-forked code. Can someone point me in the right direction to solve this? I'm stumped.

Thanks,
Jeremy

**Comment by axiomatic-io** [comment]
Nevermind. I don't know what the issue was but I reverted to an older commit. Fixed.

**Comment by Portalboy** [comment]
Could you provide the commit you reverted to? I am currently getting RavenDB related Object Not Set errors, trying to get this working... Thanks!

**Comment by axiomatic-io** [comment]
I reverted to the current head of the WheelMUD/WheelMUD project

**Comment by Portalboy** [comment]
Got it, thanks.
