### ISSUE TITLE
WheelMud license seems incomparable with long term goals.

### ISSUE THREAD

**Issue by duaneking** [WheelMud/WheelMUD#6]
Do we have to keep this license? I mean, even MSFT doesn't use it for their ope source stuff.  Or are we screwed?

**Comment by DavidRieman** [comment]
I have never changed a license before but assume there are legal things to consider. Could you expand on what is incompatible and which license you would prefer?  (Personally I hate the "viral" licenses but I have seen several common OSS licenses that I have no issus with)

**Comment by duaneking** [comment]
Well you and I talked about a few things during the kickoff that made me think about he long terms goals of the project. Can the MSPL be used for such things, really?

**Comment by DavidRieman** [comment]
Yes, the license is very permissive in what it allows for.  It is also short and simple.  It does NOT force you to provide source code online for derivative works;  IE when one makes a game based on WheelMUD they do NOT have to expose their code to potential cheaters, etc.  Also it does not force other code around it to be MS-PL (it is not virus-like).  I think we're good here with MS-PL.

**Comment by DavidRieman** [comment]
For good measure:  I am not a lawyer.  :)  Let's Close the issue if you're satisfied with this resolution?

**Comment by duaneking** [comment]
ok
