### ISSUE TITLE
Generate a shortcut from bin dir to program data dir at runtime

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#63]
It's not always obvious where the data for the MUD instance is held.  It would help to auto-generate an obvious shortcut from the running bin dir to the programdata dir where we store the databases.

**Comment by duaneking** [comment]
Why not just make this a "no-default" config option so it has to be explicitly set?

**Comment by DavidRieman** [comment]
Migrated to base repo, and flagged you with a fresh discussion on this topic
