### ISSUE TITLE
Fix change password process

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#65]
As per #61, we're moving to using a salted password hash.  The in-game password change process needs to be updated as well to:
* Require the old password to guard against "left the computer for a minute" attacks.
* Save a new salt and hashed password to the associated User.

The new usage format could be "password oldOne newOne newOne" (or we could use a series of prompts, if we build out the prompts system first).

Also, we may as well make sure that just using "password" with no arguments and/or "help password" has information about password complexity requirements, if we have any in place.  (Else we should write another ticket for building in some default password complexity requirements, but probably not very strict by default.)

**Comment by duaneking** [comment]
System can have security requirements/eventing on password attempts etc.

Server should have a set of password requirements  banned passwords, rotation, etc?

**Comment by DavidRieman** [comment]
Moved to base issues, and opened a new discussion with you tagged.  Thanks for your thoughts.
