### ISSUE TITLE
Combine Examine/Look Actions

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#67]
The Examine and Look actions do almost the same thing.  Compare the strengths of each one (such as usage of Sensory system, target searching, argument handling, and guards), and combine them into one command with both their strengths and a combined set of ActionAliases, then delete the extra file.

**Comment by duaneking** [comment]
I think the issue equates to the strength in the perception being used.

Glancing at something and investigating it intently are the same action with different levels of effort.

**Comment by DavidRieman** [comment]
Created new issue at base repo; tagged you.
