### ISSUE TITLE
Improve partial perception of SensoryMessage targets

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#70]
Often the SensoryMessage involves multiple targets, which may have different perception traits.  For example, from the "knock" command:
`ToOthers = $"{sender.Thing.Name} knocks on {this.target.Name}.",`
For now, we consider it sufficient to either have Hearing or Sight in the same room to receive the full message.  However, in actuality, there are lots of permutations with infinite potential complexity.  Some examples:
* Sender is invisible.  ("someone"?)
* Other target is invisible.  ("something"?)
* Watcher cannot hear.  ("looks like they are knocking on"?)
* Basic heat vision only detects shape of sender.  ("a humanoid"?)
* Etc.

Altogether, we _could_ go wild with being able to specify a ton of these situations and alternate texts that have to get deferred and replaced in by the sensory message / contextual message systems, for each watcher receiving the message - the target and the texts would have to be passed together for evaluations and replacements.  We should probably think critically about how far we'd want to take this.  Maybe the existing system is "good enough" through v1.0 and we should constrain any improvements against complexity vs benefit analysis.

However one thing that might be impacted lately by the large refactoring to target .NET Core and remove a bunch of dependencies (e.g. NVelocity) is the ContextualMessages often pass target objects that I think are entirely unused right now.  If we don't need to defer replacements anymore from those targets, there is a bunch of cleanup we can do to remove all that extra arg passing.

**Comment by duaneking** [comment]
I don't think Knock is done correctly here.

The knock generates sound/movement (vibration that also creates sound as waste) 

For example knocking hard enough on a door can make something on a table next to the door fall off that table.

**Comment by DavidRieman** [comment]
Rewrote and expanded on the Sensory issues at https://github.com/DavidRieman/WheelMUD/discussions/52 with more detail, and opened a discussion about Knock Impact.  Closing this one.
