### ISSUE TITLE
Submit StyleCop Settings Files

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#8]
So far duaneking and I have landed on using StyleCop with default settings, but with the following exceptions:
* Disable SA1309 "FieldNamesMustNotBeginWithUnderscore" -- Although most of the codebase uses the "this." pattern instead of underscore to denote "memberness".  Although "this." is _functionally_ more useful by applying syntax (which less able to lie) rather than naming convention (which can accidentally lie)... The fact is that most of the world has decided to stick with underscore and it has shown to be a big sticking point for people.  So we may as well conform to popularity here to be more approachable.
* Disable SA1101 "PrefixLocalCallsWithThis" -- Goes hand in hand with SA1309, in opting for the underscore-only naming convention without syntax enforcement, due to sheer popularity.
* Disable SA1200 "UsingDirectivesMustBePlacedWithinNamespace" -- We feel the rule itself provides dubious benefit, at best.  Again, this rule seems very unpopular, and combined with that it is not useful, we may as well conform to popularity as well here.

Additional recommendations for changes can be directed to our WheelMUD forums at muds.gamedev.com, but assume it will take serious convincing for changes to occur; There is significant value for having us all try to use and continually migrates towards an enforceable set of style rules, where a 3rd party (StyleCop) is allowed to make most style decisions.  Debates about style could easily go on forever if we let them, so let's try to keep them to just the most egregious offenders, so we can focus on making real progress.

**Comment by duaneking** [comment]
I think this is all in your big merge request correct?

**Comment by DavidRieman** [comment]
Yes, closing.
